### ISSUE TITLE
Interactions in chart opened in a new window are broken 

### ISSUE THREAD

**Issue by CalvinFernandez** [palantir/plottable#3134]
Expected Pan-Zoom to work correctly for charts rendered in a new window.  Interactions don't work correctly, however.

See this fiddle for more info
http://jsfiddle.net/ntmzejtj/2/

**Comment by ghost** [comment]
One fault lies in dispatcher.ts line 23 'document.addEventListener(...)'. 'document' will always be the parent window's document. When this is fixed (I made a simple hack to make it work), an exception occurs when the new window gets closed:

```
Uncaught TypeError: Cannot read property 'getComputedStyle' of undefined
    at Array._a.style (http://192.168.0.100/Scripts/d3/d3.min.js:3:11874)
    at SVGTextElement.<anonymous> (http://192.168.0.100/Scripts/plottable.js:4769:54)
    at Array._a.filter (http://192.168.0.100/Scripts/d3/d3.min.js:3:14137)
    at Numeric._hideOverlappingTickLabels (http://192.168.0.100/Scripts/plottable.js:4768:22)
    at Numeric.renderImmediately (http://192.168.0.100/Scripts/plottable.js:4673:22)
    at http://192.168.0.100/Scripts/plottable.js:1096:35
    at callbackWrapper (http://192.168.0.100/Scripts/plottable.js:257:86)
    at Set.forEach (native)
    at Set.forEach (http://192.168.0.100/Scripts/plottable.js:258:34)
    at flush (http://192.168.0.100/Scripts/plottable.js:1094:42)
```
But panning and zooming does work as expected.
